


  CREATE TABLE IF NOT EXISTS marcas(
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      nombre text NOT NULL CHECK (nombre <> ''), 
      descripcion text NOT NULL CHECK (descripcion <> ''),
      logo_imagen text NOT NULL CHECK (logo_imagen <> ''),
      UNIQUE(nombre));



  CREATE TABLE IF NOT EXISTS productos(
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      nombre text NOT NULL CHECK (nombre <> ''), 
      descripcion text NOT NULL CHECK (descripcion <> ''),
      precio decimal NOT NULL CHECK (precio <> 0),
      marca_id INTEGER REFERENCES marcas(id)
      );

	  CREATE TABLE IF NOT EXISTS imagenes_productos
(
     id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    image_url text NOT NULL CHECK (image_url <> ''),
    producto_id integer,
    CONSTRAINT producto_id FOREIGN KEY (producto_id)
        REFERENCES public.productos (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID
);




      INSERT INTO marcas(nombre, descripcion, logo_imagen)
      VALUES('Puma', 'es una empresa alemana fabricante de accesorios, ropa y calzado deportivo,
       cuya sede principal está en Herzogenaurach, Alemania.', 
       'https://drive.google.com/uc?export=view&id=1nhWvda197wSUx3RsVRRduGssoLaOCEN5');
       
             INSERT INTO marcas(nombre, descripcion, logo_imagen)
      VALUES('Adidas', 's una compañía multinacional alemana fundada en 1949 dedicada a la fabricación de equipamiento deportivo 
      y productos de moda (bolsos, camisas, relojes, gafas, etc.). La empresa también es patrocinadora de eventos y
       figuras deportivas a nivel mundial. 
      Es el primer mayor fabricante del rubro en el mundo.', 
       'https://drive.google.com/uc?export=view&id=13VLEUu9DcsBGYKvIR-Ekh2HqOE9RFyde');
       
             INSERT INTO marcas(nombre, descripcion, logo_imagen)
      VALUES('Nike', 'Fue fundada el 25 de enero de 1964 como "Blue Ribbons Sports" (BRS),7​8​ por el deportista de la 
      Universidad de Oregón Phil Knight y su entrenador,
       William Jay "Bill" Bowerman. La empresa comenzó distribuyendo calzado de la firma Onitsuka Tiger 
       (actualmente ASICS) hasta 1971, cuando BRS lanzó su primer producto propio, 
      con el emblema de la marca diseñado por Carolyn Davidson.', 
       'https://drive.google.com/uc?export=view&id=17S3RXfCrjt5qDGAF7nsU3Kr9ebc_TJtR');
       
  
       
       
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAwIiwidXNlcm5hbWUiOiJzdG9yeWRvdHMiLCJpYXQiOjE2Mzg5MDQ1NzF9.G-f3ZnwCBQKBYQVBpr2JDI62mmFudCAD5XgzWebx4q0